version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: 
      context: ./frontend
      target: build-stage
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run serve
    depends_on:
      - backend 